push

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -17,11 +17,15 @@ jobs:
               with:
                   node-version: '14.x'
                   registry-url: 'https://registry.npmjs.org'
-            - name: Copy UI folder to dist
-              run: npm run copy-ui
             - name: Install dependencies and build
               run: npm ci && npm run build
             - name: Publish package on NPM 📦
               run: npm publish
+                  if npm publish; then
+                  echo "npm publish succeeded!"
+                  else
+                  echo "npm publish failed!"
+                  exit 1
+                  fi
               env:
                   NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
